version: '3.8'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - my-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - my-network

networks: 
  my-network:
    driver: bridge

